import "./globals.css";
import type { Metadata } from "next";
import Link from "next/link";
import { Inter } from "next/font/google";

import styles from "./page.module.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Books",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const links = [
    { href: "/", label: "Home" },
    { href: "/about", label: "About" },
    { href: "/books", label: "Books" },
  ];

  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="mb-20">
          <nav>
            <ul className="flex items-left">
              {links.map(({ href, label }) => (
                <li key={href} className="px-4 text-2xl">
                  <Link href={href}>{label}</Link>
                </li>
              ))}
            </ul>
          </nav>
        </header>
        <main className={styles.main}>
          <div>{children}</div>
        </main>
      </body>
    </html>
  );
}
